Properly reject the promise in client initialisation
spotify-api/spotify-api.js pull request #167
Opened 2022-08-14 09:11 UTC by Arakmar

## Changes

In case of an authentication error or an API outage during client initialisation, it's not possible to catch the error.

## Status

- [X] These changes have been tested and documented properly.
- [X This pull request introduces some breaking changes.

2022-10-12 15:11 UTC, adb-sh commented
looks good. this should fix https://github.com/spotify-api/spotify-api.js/discussions/14#discussioncomment-3826977

2022-10-17 10:00 UTC, adb-sh requested changes
looks good in general. just added some notes for the `ClientOptions` type

2022-11-02 12:22 UTC, adb-sh approved these changes

2022-11-11 12:45 UTC, merged

2022-11-11 12:55 UTC, scientific-dev commented
@Arakmar, By the way, i don't think, there are any possible ways to get any error at `client._init` as it is protected by try and catch in `client.fetch` itself. Have you ever encountered an error despite the try and catch?

2022-11-11 13:22 UTC, scientific-dev commented
The changes have been update in [v9.2.5](https://github.com/spotify-api/spotify-api.js/releases/tag/9.2.5). If you encounter any bugs, open a new issue to resolve it. 

Thanks for your support 👍 !

2022-11-11 13:28 UTC, scientific-dev commented
> 

Just now, noticed it. 
Still, thanks for your response!